// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMf6pnIG4QdQaiOzCqm2UPrPm9ya3ZO_g',
    appId: '1:706867666450:web:cf8446af0684faf7d1c2cb',
    messagingSenderId: '706867666450',
    projectId: 'chatapp-aa5ee',
    authDomain: 'chatapp-aa5ee.firebaseapp.com',
    storageBucket: 'chatapp-aa5ee.appspot.com',
    measurementId: 'G-ZW0GMZXH09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5qa-4jQZztPQ9K-ac_h4IY8kNomoYh_A',
    appId: '1:706867666450:android:632bba4c2e1091d7d1c2cb',
    messagingSenderId: '706867666450',
    projectId: 'chatapp-aa5ee',
    storageBucket: 'chatapp-aa5ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQP19LoH34i_WgZVJZkKluC-IUGYIiQDM',
    appId: '1:706867666450:ios:30c1058875c54048d1c2cb',
    messagingSenderId: '706867666450',
    projectId: 'chatapp-aa5ee',
    storageBucket: 'chatapp-aa5ee.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
